server:
  port: 8099
  servlet:
    context-path: /SistReport
spring:
  datasource:
    url: jdbc:sqlserver://localhost\ReporteTiempos
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.
    open-in-view: false

logging:
  level:
    root: WARN
    com: INFO
    org:
      springframework:
      # web: DEBUG
      hibernate: ERROR
