server:
  port: 8099
  servlet:
    context-path: /SistReport
spring:
  datasource:
    url: jdbc:sqlserver://localhost;database=ReporteTiempos
    username: sa
    password: POIzxc01!
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false

logging:
  level:
    root: WARN
    com: INFO
    org:
      springframework:
      # web: DEBUG
      hibernate: ERROR
management:
  endpoints:
    web:
      exposure:
        include: "*"
