server:
  servlet:
    context-path: /sistema-reporte-tiempos
spring:
  application:
    name: sistreport-service
  datasource:
    #url: jdbc:mysql://localhost:3306/sist-report
    #username: root
    url: jdbc:sqlserver://localhost;database=ReporteTiempos
    username: sa
    password: POIzxc01!
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: org.hibernate.dialect.SQLServerDialect

    open-in-view: false

logging:
  level:
    root: WARN
    com: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

  file:
    name: application.log
    max-history: 1
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'

management:
  endpoints:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
jwt:
  route:
    authentication:
      path: /auth
  header: Authorization
  expiration: 604800
  secret: sistreport
